# Generated by Django 5.2.4 on 2025-08-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
