# Generated by Django 5.2.4 on 2025-08-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_audio_file_alter_song_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='description',
            new_name='lyrics',
        ),
    ]
