# Generated by Django 5.2.4 on 2025-08-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm'), ('romantic', 'Romantic'), ('melancholic', 'Melancholic'), ('angry', 'Angry'), ('hopeful', 'Hopeful'), ('nostalgic', 'Nostalgic'), ('chill', 'Chill'), ('dark', 'Dark'), ('uplifting', 'Uplifting'), ('epic', 'Epic'), ('dreamy', 'Dreamy'), ('lonely', 'Lonely'), ('sensual', 'Sensual'), ('confident', 'Confident'), ('breakup', 'Breakup'), ('sarcastic', 'Sarcastic'), ('empowered', 'Empowered'), ('rebellious', 'Rebellious')], max_length=50),
        ),
    ]
