# Generated by Django 5.2.4 on 2025-08-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='duracion',
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.CharField(default='rock', max_length=100),
            preserve_default=False,
        ),
    ]
