# Generated by Django 5.2.4 on 2025-08-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0002_remove_cancion_duracion_cancion_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='año_publicacion',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='emocion',
            field=models.CharField(default='alegria', max_length=100),
            preserve_default=False,
        ),
    ]
