# Generated by Django 5.2.4 on 2025-08-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('lyrics', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to='songs/audio/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='songs/covers/')),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm'), ('romantic', 'Romantic'), ('melancholic', 'Melancholic'), ('angry', 'Angry'), ('hopeful', 'Hopeful'), ('nostalgic', 'Nostalgic'), ('chill', 'Chill'), ('dark', 'Dark'), ('uplifting', 'Uplifting'), ('', '---'), ('epic', 'Epic'), ('dreamy', 'Dreamy'), ('lonely', 'Lonely'), ('sensual', 'Sensual'), ('confident', 'Confident'), ('breakup', 'Breakup'), ('sarcastic', 'Sarcastic'), ('empowered', 'Empowered'), ('rebellious', 'Rebellious')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
