# Generated by Django 5.2.4 on 2025-08-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
