# Generated by Django 5.2.4 on 2025-08-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_like_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes_count',
        ),
    ]
