# Generated by Django 5.2.4 on 2025-08-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Feliz'), ('sad', 'Triste'), ('energetic', 'Enérgico'), ('calm', 'Calmado'), ('romantic', 'Romántico'), ('melancholic', 'Melancólico'), ('angry', 'Enojado'), ('hopeful', 'Esperanzado'), ('nostalgic', 'Nostálgico'), ('chill', 'Relajado'), ('dark', 'Oscuro'), ('uplifting', 'Inspirador'), ('', '---'), ('epic', 'Épico'), ('dreamy', 'Soñador'), ('lonely', 'Solitario'), ('sensual', 'Sensual'), ('confident', 'Seguro'), ('breakup', 'Ruptura'), ('sarcastic', 'Sarcástico'), ('empowered', 'Empoderado'), ('rebellious', 'Rebelde')], max_length=50),
        ),
    ]
