# Generated by Django 5.2.4 on 2025-09-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_song_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('energetico', 'Energetico'), ('calmado', 'Calmado'), ('romantico', 'Romantico'), ('melancolico', 'Melancolico'), ('enojado', 'Enojado'), ('esperanzado', 'Esperanzado'), ('nostalgico', 'Nostalgico'), ('relajado', 'Relajado'), ('oscuro', 'Oscuro'), ('inspirador', 'Inspirador'), ('epico', 'Epico'), ('sonador', 'Sonador'), ('solitario', 'Solitario'), ('sensual', 'Sensual'), ('seguro', 'Seguro'), ('ruptura', 'Ruptura'), ('sarcastico', 'Sarcastico'), ('empoderado', 'Empoderado'), ('rebelde', 'Rebelde')], max_length=50),
        ),
    ]
