# Generated by Django 5.2.4 on 2025-09-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_song_mood'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='song',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
