# Generated by Django 5.2.4 on 2025-09-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_song_alter_favorite_song_alter_like_song'),
        ('main', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
