# Generated by Django 5.2.5 on 2025-10-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(blank=True, default="'bio': 'Proyecto musical que busca conectar con las emociones y experiencias de la vida a través de sonidos auténticos y letras sinceras. Con un estilo que mezcla influencias de distintos géneros, su propuesta refleja una identidad versátil y en constante evolución'"),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='artists/profiles/artist_foto.jpg', null=True, upload_to='artists/profiles/'),
        ),
    ]
