# Generated by Django 5.2.5 on 2025-10-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artistprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('tickets', models.CharField(max_length=150)),
                ('artist', models.ManyToManyField(related_name='eventos', to='artist.artistprofile')),
            ],
        ),
    ]
