# Generated by Django 5.2.5 on 2025-10-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='tickets',
            field=models.CharField(default='www.tickets.com', max_length=150),
        ),
    ]
