# Generated by Django 5.2.5 on 2025-10-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_eventos_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Events',
        ),
    ]
