# Generated by Django 5.2.5 on 2025-10-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_rename_eventos_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_poster',
            field=models.ImageField(blank=True, default='artists/events/poster_default.jpg', null=True, upload_to='artists/events/'),
        ),
    ]
